### ISSUE TITLE
[FEATURE]: Tutorial how to achieve screens like on readme

### ISSUE THREAD

**Issue by Naimadnap** [vingerha/ha_adsb_lol#2]
To be hones I have no idea how to add a map card to show all flights in my area and also detailed info like on FR24.

**Comment by vingerha** [comment]
History: I discovered that FR24 is able to also have free API without a need to feed into it but ... I want to show a moving airplane both locally as well as for a specific aircraft....  As the FR24 integration rejected a PR for the moving bits, built something myself. Agree it is not a sexy card but it does for me what I want. 
I am not sure what data you are missing but also here I did filter out attributes that I (me only) am not interested in, below also a rep. of the data that I receive before I filter/rework it, the format/labelling is common for adbs sources so let me know what you are missing and kindly explain 'why' as for my understanding. Adding all-date just-because is not my view :)

![image](https://github.com/vingerha/ha_adsb_lol/assets/44190435/36132e3e-d752-411f-ab5c-5dd88c344e79)

![image](https://github.com/vingerha/ha_adsb_lol/assets/44190435/dfa66b87-9daf-4141-9593-9bbbb9bfa2d7)

```
{
  "ac": [
    {
      "alert": 0,
      "alt_baro": 0,
      "alt_geom": 0,
      "baro_rate": 0,
      "category": "string",
      "emergency": "string",
      "flight": "string",
      "gs": 0,
      "gva": 0,
      "hex": "string",
      "lat": 0,
      "lon": 0,
      "messages": 0,
      "mlat": [
        "string"
      ],
      "nac_p": 0,
      "nac_v": 0,
      "nav_altitude_mcp": 0,
      "nav_heading": 0,
      "nav_qnh": 0,
      "nic": 0,
      "nic_baro": 0,
      "r": "string",
      "rc": 0,
      "rssi": 0,
      "sda": 0,
      "seen": 0,
      "seen_pos": 0,
      "sil": 0,
      "sil_type": "string",
      "spi": 0,
      "squawk": "string",
      "t": "string",
      "tisb": [
        "string"
      ],
      "track": 0,
      "type": "string",
      "version": 0,
      "geom_rate": 0,
      "dbFlags": 0,
      "nav_modes": [
        "string"
      ],
      "true_heading": 0,
      "ias": 0,
      "mach": 0,
      "mag_heading": 0,
      "oat": 0,
      "roll": 0,
      "tas": 0,
      "tat": 0,
      "track_rate": 0,
      "wd": 0,
      "ws": 0,
      "gpsOkBefore": 0,
      "gpsOkLat": 0,
      "gpsOkLon": 0,
      "lastPosition": {
        "lat": 0,
        "lon": 0,
        "nic": 0,
        "rc": 0,
        "seen_pos": 0
      },
      "rr_lat": 0,
      "rr_lon": 0,
      "calc_track": 0,
      "nav_altitude_fms": 0
    }
  ],
  "ctime": 0,
  "msg": "string",
  "now": 0,
  "ptime": 0,
  "total": 0
}
```

**Comment by DamianHofy** [comment]
now is clear,
please add this screenshots to readme and paragraph that this HA plugin is required 
https://github.com/thomasloven/lovelace-auto-entities

that's it. Based on this knowlage I will be able to add what I need to the map. You can close this issue
